set $cache_enabler_uri "";
set $cache_enabler_webp "";

if ($http_accept ~* "image/webp") {
    set $cache_enabler_webp ".webp";
}

location / {
    try_files "/wp-content/cache/cache-enabler/${host}${uri}index${cache_enabler_webp}.html" $uri $uri/ /index.php?$args;
    add_header X-Cache-Mode "cache-enabler";
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass php;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_intercept_errors on;
    fastcgi_request_buffering off;
    fastcgi_buffers 16 16k;
    fastcgi_buffer_size 32k;
    fastcgi_read_timeout 300s;
    fastcgi_keep_conn on;
}
